# Exploration of averaging method

In [5]:
import pandas as pd


df = pd.read_pickle('tmp_data/V15X_predictions.pkl')


df_yearly = pd.read_pickle('tmp_data/V15X_predictions_yearly_average.pkl')

In [6]:
df.iloc[0]

latitude_ERA                             -17.002337
longitude_ERA                             -151.3125
time                            2019-01-01 00:00:00
MODIS_LST                                299.983887
skt_unnormalised                         302.135925
number_of_modis_observations                      2
predictions                              300.613403
predicion_bias                            -0.629517
predicion_error                            0.629517
Name: 0, dtype: object

In [8]:
#Target point: 67.2, 24.59

In [19]:
df.query("24.4 < latitude_ERA < 24.6 & 67.1 < longitude_ERA < 67.3")

,latitude_ERA,longitude_ERA,time,MODIS_LST,skt_unnormalised,number_of_modis_observations,predictions,predicion_bias,predicion_error
34328,24.590156,67.2,2019-01-01 09:00:00,296.716278,295.881592,5,305.666534,-8.950256,8.950256
134072,24.590156,67.2,2019-01-02 09:00:00,298.285126,296.533875,16,308.697021,-10.411896,10.411896
234952,24.590156,67.2,2019-01-03 09:00:00,299.571350,296.277588,19,307.788391,-8.217041,8.217041
433818,24.590156,67.2,2019-01-05 09:00:00,298.082581,296.439056,7,309.858032,-11.775452,11.775452
628122,24.590156,67.2,2019-01-07 09:00:00,295.535614,295.183350,17,302.499939,-6.964325,6.964325
...,...,...,...,...,...,...,...,...,...
2649357,24.590156,67.2,2019-12-27 09:00:00,291.135284,292.654114,6,301.707703,-10.572418,10.572418
2750468,24.590156,67.2,2019-12-28 09:00:00,295.285583,292.466125,16,306.962769,-11.677185,11.677185
2848251,24.590156,67.2,2019-12-29 09:00:00,293.837280,292.431610,18,304.304871,-10.467590,10.467590
2942990,24.590156,67.2,2019-12-30 09:00:00,293.991241,292.365112,19,304.814209,-10.822968,10.822968
3044526,24.590156,67.2,2019-12-31 09:00:00,290.778046,291.504150,4,305.549316,-14.771271,14.771271

In [21]:
df_yearly.query("24.4 < latitude_ERA < 24.6 & 67.1 < longitude_ERA < 67.3")

,latitude_ERA,longitude_ERA,MODIS_LST,skt_unnormalised,number_of_modis_observations,predictions,predicion_bias,predicion_error
72445,24.590156,67.2,300.773254,299.203217,12.865248,311.070892,-10.297641,10.297641

In [ ]:
V15X_predictions.to_pickle('tmp_data/V15X_predictions.pkl')
V15X_predictions_averaged.to_pickle('tmp_data/V15X_predictions_yearly_average.pkl')

In [22]:
root = '/network/group/aopp/predict/TIP016_PAXTON_RPSPEEDY/ML4L/ECMWF_files/raw/processed_data/joined_data/'
original_testng_file = root+'2019_ML.parquet'
new_testing_file = root+'2019_RML.parquet'

In [23]:
df_og = pd.read_parquet(original_testng_file)

In [24]:
df_new = pd.read_parquet(new_testing_file)

In [25]:
df_og

,sp,msl,u10,v10,t2m,aluvp,aluvd,alnip,alnid,istl1,...,z_v20,slor_v20,clake_monthly_value,cl_saline,cl_saline_max,MODIS_LST,latitude_ERA,longitude_ERA,time,skt_unnormalised
0,0.809827,-0.567343,-1.644127,-0.540686,0.465600,-0.405106,-0.468158,-1.542558,-1.69344,0.053039,...,0.231711,-0.013803,-0.260782,-0.063803,-0.06977,299.983887,-17.002337,-151.31250,2019-01-01 00:00:00,302.135925
1,0.796208,-0.588126,-1.584559,-0.559724,0.458420,-0.405106,-0.468158,-1.542558,-1.69344,0.053039,...,-0.050767,-0.013803,-0.200067,-0.063803,-0.06977,299.679443,-16.721306,-151.59375,2019-01-01 00:00:00,302.208191
2,0.798137,-0.578759,-1.644741,-0.478133,0.457622,-0.405106,-0.468158,-1.542558,-1.69344,0.053039,...,0.010366,-0.013803,0.003028,-0.063803,-0.06977,300.015289,-16.721306,-151.31250,2019-01-01 00:00:00,302.094910
3,0.801088,-0.570270,-1.702467,-0.445837,0.462181,-0.405106,-0.468158,-1.542558,-1.69344,0.053039,...,-0.092085,-0.013803,-0.057167,-0.063803,-0.06977,299.370514,-16.721306,-151.03125,2019-01-01 00:00:00,301.973816
4,0.766927,-1.017544,-2.207878,1.264841,0.441894,-0.405106,-0.468158,-1.542558,-1.69344,0.053039,...,0.040722,-0.013803,0.544479,-0.063803,-0.06977,306.372742,1.826697,-157.50000,2019-01-01 00:00:00,300.624207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3111692,0.698695,-1.406640,1.212226,0.495114,-2.536583,-0.634320,-0.632444,-0.891465,-0.90234,0.053706,...,0.052949,0.046975,-0.264214,-0.063803,-0.06977,238.350433,70.117048,-147.00000,2019-12-31 23:00:00,248.418365
3111693,0.742957,-1.444401,2.231337,0.584523,-2.504785,-0.405112,-0.468165,-1.542560,-1.69344,-22.144779,...,0.134741,-0.013803,-0.264214,-0.063803,-0.06977,246.749298,70.117048,-145.50000,2019-12-31 23:00:00,250.932037
3111694,0.728884,-1.478064,2.451802,0.026309,-2.486435,-0.405112,-0.468165,-1.542560,-1.69344,-21.888666,...,0.140643,-0.013803,-0.261328,-0.063803,-0.06977,250.794434,70.117048,-144.75000,2019-12-31 23:00:00,251.090240
3111695,0.669528,-1.519337,2.530407,-0.490770,-2.490196,-0.405112,-0.468165,-1.542560,-1.69344,-21.938467,...,0.430288,-0.013803,-0.214444,-0.063803,-0.06977,253.427795,70.117048,-144.00000,2019-12-31 23:00:00,251.006256
3111696,0.665782,-1.563245,2.399602,-0.637973,-2.488600,-0.405112,-0.468165,-1.542560,-1.69344,-21.877487,...,0.102277,-0.013803,-0.252751,-0.063803,-0.06977,253.657776,70.117048,-143.25000,2019-12-31 23:00:00,250.844147

In [26]:
df_new

,sp,msl,u10,v10,t2m,aluvp,aluvd,alnip,alnid,istl1,...,slor_v20,clake_monthly_value,cl_saline,cl_saline_max,MODIS_LST,latitude_ERA,longitude_ERA,time,number_of_modis_observations,skt_unnormalised
0,0.814272,-0.579895,-1.642299,-0.556515,0.460404,-0.407848,-0.470615,-1.542907,-1.693005,0.052042,...,-0.013735,-0.257334,-0.070736,-0.070736,299.983887,-17.002337,-151.31250,2019-01-01 00:00:00,2,302.135925
1,0.800466,-0.601931,-1.583076,-0.575466,0.453205,-0.407848,-0.470615,-1.542907,-1.693005,0.052042,...,-0.013735,-0.196966,-0.070736,-0.070736,299.679443,-16.721306,-151.59375,2019-01-01 00:00:00,7,302.208191
2,0.802422,-0.591999,-1.642910,-0.494248,0.452406,-0.407848,-0.470615,-1.542907,-1.693005,0.052042,...,-0.013735,0.004971,-0.070736,-0.070736,300.015289,-16.721306,-151.31250,2019-01-01 00:00:00,8,302.094910
3,0.805413,-0.582998,-1.700301,-0.462099,0.456976,-0.407848,-0.470615,-1.542907,-1.693005,0.052042,...,-0.013735,-0.054881,-0.070736,-0.070736,299.370514,-16.721306,-151.03125,2019-01-01 00:00:00,3,301.973816
4,0.770784,-1.057234,-2.202781,1.240779,0.436638,-0.407848,-0.470615,-1.542907,-1.693005,0.052042,...,-0.013735,0.543333,-0.070736,-0.070736,306.372742,1.826697,-157.50000,2019-01-01 00:00:00,1,300.624207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3111815,0.701617,-1.469785,1.197492,0.474561,-2.549312,-0.637083,-0.634939,-0.893112,-0.903402,0.052694,...,0.047055,-0.260747,-0.070736,-0.070736,238.350433,70.117048,-147.00000,2019-12-31 23:00:00,10,248.418365
3111816,0.746485,-1.509821,2.210695,0.563563,-2.517433,-0.407854,-0.470622,-1.542909,-1.693005,-21.663296,...,-0.013735,-0.260747,-0.070736,-0.070736,246.749298,70.117048,-145.50000,2019-12-31 23:00:00,9,250.932037
3111817,0.732219,-1.545513,2.429881,0.007894,-2.499038,-0.407854,-0.470622,-1.542909,-1.693005,-21.412750,...,-0.013735,-0.257878,-0.070736,-0.070736,250.794434,70.117048,-144.75000,2019-12-31 23:00:00,3,251.090240
3111818,0.672049,-1.589275,2.508031,-0.506827,-2.502808,-0.407854,-0.470622,-1.542909,-1.693005,-21.461468,...,-0.013735,-0.211261,-0.070736,-0.070736,253.427795,70.117048,-144.00000,2019-12-31 23:00:00,5,251.006256
3111819,0.668253,-1.635829,2.377985,-0.653358,-2.501209,-0.407854,-0.470622,-1.542909,-1.693005,-21.401814,...,-0.013735,-0.249349,-0.070736,-0.070736,253.657776,70.117048,-143.25000,2019-12-31 23:00:00,1,250.844147